### ISSUE TITLE
iCloud and OAuth2 (Apple SignIn) not working

### ISSUE THREAD

**Issue by DierkDroth** [jstedfast/MailKit#1397]
I'm stuck trying to get OAuth2 (Apple SignIn) working for my iCloud mail account. I know, this issue might not fall (entirely) on MailKit's plate. However, I'm just desperate for any advice

Here is what I have:
- OAuth2 works with my Microsoft 365 and my Google GMail account -> good
- I can connect to my iCloud mail account with just email + (application) password -> good
- I can retrieve the code to start the Apple Sign procedure -> good
- I even the get the full set of access_token, refresh_token and id_token wen applying the code -> good

Now the trouble starts:
- I fail to the use access_token (above) to login to MailKit (Mailkit logs below)
- I fail to get a fresh access_token bby applying the refresh_token ("invalid request"). For all I know I appled the logic exactly [as advised here ](https://developer.apple.com/documentation/sign_in_with_apple/generate_and_validate_tokens)

Also: 
- appears the iCloud application password - which is important to (legacy) login (see above) - does not appear to play any role in that procedure. This makes me thinking, that I might doing something fundementally wrong?!?
- I read somewhere that the access_token (above) in fact is not used anyway according Apple support, which makes me wonder...
- I'm also wonder if the id_token might have any relevance which I might be missing. For all I understand I just would not need it, no?

```
2022-06-24 07:15:51:415 Imap.Connected: 'imaps://imap.mail.me.com:993/'
2022-06-24 07:15:51:427 Imap.S: * OK [CAPABILITY XAPPLEPUSHSERVICE IMAP4 IMAP4rev1 SASL-IR AUTH=ATOKEN AUTH=PLAIN] (2216B54-3f88bf910c5d) ci74p00im-qukt09100901.me.com
2022-06-24 07:15:57:657 Imap.C: A00000000 AUTHENTICATE XOAUTH2 dXNlcj1kaWVyay5kcm90aEBpY2xvdWQuY29tAWF1dGg9QmVhcmVyIGFlY2Y5YTExZDJjNGY0NzA0YmE1ZDMxMDUxYjdlOTFiZS4wLnNzcXNyLjdLSEs1ZTVOOE51dU9XdWpTVDVxalEBAQ==
2022-06-24 07:15:57:782 Imap.S: A00000000 BAD Unsupported authentication
2022-06-24 07:15:58:032 (1f15941b-1a94-4ff9-ad7a-dd1a9d5f3d5f) Mail.MailClient.ConnectAsync.AuthenticateAsync.Exception: mailAccount='<email>' MailKit.Security.AuthenticationException: Authentication failed.
   at MailKit.Net.Imap.ImapClient.AuthenticateAsync(SaslMechanism mechanism, Boolean doAsync, CancellationToken cancellationToken)
   at Unusual.Mail.MailClient.ConnectAsync()
```

**Comment by jstedfast** [comment]
Hi @DierkDroth 

The problem is that the Apple IMAP server does not advertise support for the XOAUTH2 SASL mechanism.

They seem to only support PLAIN and something called ATOKEN (which I can find no documentation for).

The only registered SASL mechanisms are listed here:

https://www.iana.org/assignments/sasl-mechanisms/sasl-mechanisms.xhtml

My *guess* is that ATOKEN is probably similar to XOAUTH2, but Apple's own spin on it. I just don't know how to serialize the access token.

**Comment by DierkDroth** [comment]
@jstedfast thanks for your feedback. 

So I take it you haven't been able to hook up to Apple OAuth2/SignIn nor have you heard of anyone who was able to achieve that ... well, guess Apple is spinning again it's own wheel, as always ... sad.

Anyway, I'd let you know if I figured out anything.

**Comment by jstedfast** [comment]
Seems like you might be the first to try to authenticate to an Apple IMAP server using OAuth :)

**Comment by 537mfb** [comment]
> My _guess_ is that ATOKEN is probably similar to XOAUTH2, but Apple's own spin on it. I just don't know how to serialize the access token.

maybe here: https://developer.apple.com/documentation/sign_in_with_apple/generate_and_validate_tokens

**Comment by DierkDroth** [comment]
@537mfb thanks. That's what I tried. Unfortunately to no avail...

**Comment by jstedfast** [comment]
@537mfb that documentation explains how to get a JWT auth token, for sure, but it's meant to be used with Apple's web APIs (I know this because I just implemented support for the [AppStoreConnect API](https://developer.apple.com/app-store-connect/api/) for Visual Studio).

What it doesn't tell you is how to use that token to authenticate with the `ATOKEN` mechanism.

It might even be that their JWT tokens aren't even meant to be used with `ATOKEN` authentication via IMAP.

We don't know :(

**Comment by DierkDroth** [comment]
Thanks for looking into @jstedfast.

At this point I moved on. I might revisit the subject again at a later point though...

**Comment by DierkDroth** [comment]
@jstedfast I again looked into that issue:
- I ironed out the token issues on my side: I'm able to get a valid token and refresh token (using REST API) and now can use Apple as identity provider -> good
- however, I still fail to use the token to authenticate the MailKit IMAP client
- I also tried deriving a custom `SaslMechanismAToken `from `SaslMechanismOAuthBearer `or `SaslMechanismOAuth2 ` as per your suggestio above... both to no avail
- I held off digging any deeper at this point

So, unfortunately still a 'no go'. 
Please let me know in case you had any new findings. Thanks

**Comment by jstedfast** [comment]
Yea, I've never seen any documentation on the format for the ATOKEN auth mechanism for IMAP/SMTP/etc

**Comment by AdityaGarg8** [comment]
@DierkDroth I was wondering if you were able to make SMTP work with OAuth2 btw.

**Comment by DierkDroth** [comment]
No, I could not get it to work

**Comment by AdityaGarg8** [comment]
> No, I could not get it to work

Such a shame that a company like Apple doesn't even provide this feature. They for some reason love to stay different from others.
